[package]
name = "murmur2"
version = "0.1.0"
edition = "2021"
description = "murmur2 hash functions"
keywords = ["murmur2", "murmur", "hash", "hashing"]
repository = "https://github.com/jcaesar/murmur2rs"

[workspace]
members = [ "test" ]
